include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_import: warning
    dead_code: warning
    missing_required_param: error
    missing_return: error
    lines_longer_than_80_chars: ignore
    file_names: warning
    unused_local_variable: warning
    unused_field: warning
    unused_element: warning

linter:
  rules:
    file_names: true
    constant_identifier_names: false
    non_constant_identifier_names: false
    avoid_print: true
    prefer_const_constructors: false
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: false
    always_declare_return_types: true
    avoid_empty_else: true
    avoid_unnecessary_containers: true
    use_key_in_widget_constructors: true
    sort_child_properties_last: true
    lines_longer_than_80_chars: true

formatter:
  page_width:
    100
    # avoid_print: true
    # prefer_const_constructors: true
    # prefer_const_literals_to_create_immutables: true